@baseUrl = http://localhost:3000/api


### =====================================================
### REPORT EXPORTS
### =====================================================

### 1. Export Task Report
# ADMIN LOGIN MUST BE ACTIVE
GET {{baseUrl}}/reports/export/tasks

###

### 2. Export Users Report
# ADMIN LOGIN MUST BE ACTIVE
GET {{baseUrl}}/reports/export/users

###